import html
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, EmailStr, Field

from app.config import settings
from app.services.ai_service import AIService
from app.services.data_loader import DataLoader
from app.services import graph_mail, notification_mail, smtp_mail

router = APIRouter(prefix="/api/maintenance", tags=["maintenance"])
data_loader = DataLoader()
ai_service = AIService()


class WorkOrderNotifyRequest(BaseModel):
    """Payload from UI when user requests an email notification for a scheduled work order."""

    to_email: Optional[EmailStr] = Field(
        default=None,
        description="Override recipient; otherwise GRAPH_NOTIFY_DEFAULT_TO is used",
    )
    asset_id: str
    plant: str = ""
    state: str = ""
    asset_type: Optional[str] = None
    maintenance_type: str = ""
    status: str = ""
    scheduled_date: str = ""
    month: Optional[str] = None
    day: Optional[str] = None
    year: Optional[str] = None
    estimated_duration_hours: Optional[float] = None
    use_llm: bool = Field(
        default=True,
        description="When true and Azure OpenAI is configured, append an AI-written summary (what happened, context, actions).",
    )


@router.get("/mail-status")
async def mail_status():
    """
    Quick check that Graph/SMTP settings are visible to the API (no secrets returned).
    Use after deploy: GET /api/maintenance/mail-status
    """
    g = graph_mail.graph_configured()
    s = smtp_mail.smtp_configured()
    has_default_to = bool((settings.graph_notify_default_to or "").strip())
    return {
        "mail_ready": g or s,
        "graph_configured": g,
        "smtp_configured": s,
        "has_default_recipient": has_default_to,
        "env_file_hint": "backend/.env next to the FastAPI app (restart server after edits)",
    }


@router.post("/notify-work-order")
async def notify_work_order(body: WorkOrderNotifyRequest):
    """
    Send notification email via Microsoft Graph (if configured) or SMTP (fallback).
    Set GRAPH_* + GRAPH_MAILBOX_UPN, or set SMTP_HOST / SMTP_USER / SMTP_PASSWORD in backend/.env.
    """
    if not notification_mail.mail_configured():
        raise HTTPException(
            status_code=503,
            detail=(
                "Mail is not configured. Either set Microsoft Graph: GRAPH_TENANT_ID, GRAPH_CLIENT_ID, "
                "GRAPH_CLIENT_SECRET, GRAPH_MAILBOX_UPN — or set SMTP: SMTP_HOST, SMTP_USER, SMTP_PASSWORD "
                "(optional SMTP_FROM, SMTP_PORT=587). Also set GRAPH_NOTIFY_DEFAULT_TO or enter a recipient in the UI."
            ),
        )

    to_addr = (body.to_email or settings.graph_notify_default_to or "").strip()
    if not to_addr:
        raise HTTPException(
            status_code=400,
            detail="No recipient: provide to_email in the request or set GRAPH_NOTIFY_DEFAULT_TO on the server.",
        )

    when_parts = [p for p in [body.month, body.day, body.year] if p]
    when_line = " ".join(when_parts) if when_parts else ""

    subject = f"[Maintenance] Work order notice · {body.asset_id} · {body.maintenance_type or 'Work order'}"

    lines = [
        "Scheduled work order notification (from PEPSICO management dashboard)",
        "",
        f"Asset ID: {body.asset_id}",
        f"Plant: {body.plant}",
        f"State / region: {body.state}",
        f"Asset type: {body.asset_type or '—'}",
        f"Maintenance type: {body.maintenance_type}",
        f"Status: {body.status}",
        f"Scheduled (raw): {body.scheduled_date or '—'}",
    ]
    if when_line:
        lines.append(f"Calendar: {when_line}")
    if body.estimated_duration_hours is not None:
        lines.append(f"Estimated duration: ~{body.estimated_duration_hours} h")
    lines.extend(
        [
            "",
            "This message was generated by an operator action in the maintenance view.",
            "— Automated notification",
        ]
    )
    body_text = "\n".join(lines)

    wo_for_llm: Dict[str, Any] = {
        "asset_id": body.asset_id,
        "plant": body.plant,
        "state": body.state,
        "asset_type": body.asset_type,
        "maintenance_type": body.maintenance_type,
        "status": body.status,
        "scheduled_date": body.scheduled_date,
        "calendar": when_line or None,
        "estimated_duration_hours": body.estimated_duration_hours,
    }
    llm_narrative: Optional[str] = None
    if body.use_llm:
        asset_rows = data_loader.get_assets_filtered(asset_id=body.asset_id)
        asset_ctx = asset_rows[0] if asset_rows else None
        anoms = [
            r
            for r in data_loader.load_anomalies()
            if str(r.get("asset_id", "")).strip() == str(body.asset_id).strip()
        ][:8]
        llm_narrative = ai_service.generate_work_order_narrative(
            work_order=wo_for_llm,
            asset_context=asset_ctx,
            recent_anomalies=anoms,
        )
    if llm_narrative:
        body_text += (
            "\n\n"
            + "—" * 40
            + "\nAI-generated summary (context & recommended actions)\n"
            + "—" * 40
            + "\n"
            + llm_narrative
        )

    table_rows_html = "".join(
        f"<tr><td style='padding:4px 12px 4px 0;font-weight:600;'>{html.escape(k)}</td>"
        f"<td>{html.escape(str(v))}</td></tr>"
        for k, v in [
            ("Asset ID", body.asset_id),
            ("Plant", body.plant or "—"),
            ("State", body.state or "—"),
            ("Asset type", body.asset_type or "—"),
            ("Type", body.maintenance_type or "—"),
            ("Status", body.status or "—"),
            ("Scheduled", body.scheduled_date or "—"),
            ("Calendar", when_line or "—"),
            (
                "Duration",
                f"~{body.estimated_duration_hours} h" if body.estimated_duration_hours is not None else "—",
            ),
        ]
    )
    llm_block_html = ""
    if llm_narrative:
        llm_block_html = (
            "<h3 style='color:#003087;margin-top:24px;'>AI summary — what this means &amp; what to do</h3>"
            f"<pre style='white-space:pre-wrap;font-family:Segoe UI,Roboto,sans-serif;font-size:13px;"
            "background:#f1f5f9;padding:12px 16px;border-radius:8px;border:1px solid #e2e8f0;'>"
            f"{html.escape(llm_narrative)}</pre>"
        )

    body_html = (
        "<html><body style='font-family:Segoe UI,Roboto,sans-serif;font-size:14px;color:#1e293b;'>"
        "<h2 style='color:#003087;'>Scheduled work order</h2>"
        "<table style='border-collapse:collapse;'>"
        + table_rows_html
        + "</table>"
        + llm_block_html
        + "<p style='margin-top:16px;color:#64748b;font-size:12px;'>Sent from the maintenance dashboard "
        "(Microsoft Graph or SMTP). AI section uses Azure OpenAI when configured.</p></body></html>"
    )

    try:
        result = notification_mail.send_work_order_notification(
            to_address=to_addr,
            subject=subject,
            body_text=body_text,
            body_html=body_html,
        )
    except RuntimeError as e:
        raise HTTPException(status_code=502, detail=str(e)) from e

    out: Dict[str, Any] = {"ok": True, "recipient": to_addr, **result}
    if body.use_llm:
        out["llm_summary_included"] = bool(llm_narrative)
    return out


@router.get("")
async def get_maintenance_schedule(
    state: Optional[str] = Query(None, description="Filter by state"),
    plant: Optional[str] = Query(None, description="Filter by plant"),
    asset_id: Optional[str] = Query(None, description="Filter by asset ID"),
):
    """Get maintenance schedule data"""
    rows: List[Dict[str, Any]] = data_loader.load_maintenance()
    if not rows:
        return []

    def col(name: str) -> bool:
        return name in rows[0]

    out = rows
    if state and col("state"):
        out = [r for r in out if r.get("state") == state]
    if plant and col("plant"):
        out = [r for r in out if r.get("plant") == plant]
    if asset_id and col("asset_id"):
        out = [r for r in out if r.get("asset_id") == asset_id]
    return out
